import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ReactNode } from "react";
import { Provider } from "jotai";
import { OptimisticFavoriteTokensProvider } from "./components/OptimisticFavoriteTokensProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <OptimisticFavoriteTokensProvider />

        <body
          className={clsx(
            montserrat.className,
            "min-h-screen flex  flex-col bg-gradient-to-br from-yellow-200 to-yellow-50"
          )}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
